name: NixOS Rebuild

on:
  pull_request:
    branches:
      - master

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run nixos-rebuild switch
      run: nixos-rebuild switch
